# .github/workflows/deploy.yml

name: deploy
on:
  push:
    branches:
      # Pushing to the `main` branch
      # will trigger our workflow
      - main
    paths-ignore:
      - 'bin/**'
      - 'README.m'
jobs:
    build:
      runs-on: ubuntu-latest      
      steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2            
          with:
            # Fetch the entire Git history
            fetch-depth: 0       
  
        - name: Composer (php-actions)
          uses: php-actions/composer@v6
  
        - name: Setup Node.js environment
          uses: actions/setup-node@v4.1.0 
  
        - name: Install Node.js dependencies
          run: yarn install
  
        - name: Build theme
          run: yarn run build
  
        - name: Upload a Build Artifact
          uses: actions/upload-artifact@v4.4.3
          with:
            name: my-theme-build
            path: |
              dist/
              vendor/
            retention-days: 1
            
    deploy:   
    
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Checkout
            uses: actions/checkout@v4.2.2  
            with:
              fetch-depth: 0    
              
          -  name: Download artifact
             uses: actions/download-artifact@v3
             with:
                name: my-theme-build
                path: .
                
          - name: lftp-mirror-action
            uses: pressidium/lftp-mirror-action@v1
            with:
              host: ${{ secrets.SFTP_HOST }} 
              user: ${{ secrets.SFTP_USER }}
              pass: ${{ secrets.SFTP_PASS }}
              remoteDir: '/bitnami/wordpress/wp-content/themes'
              options: '--verbose'
            
          
