# .github/workflows/deploy.yml

name: deploy
on:
  push:
    branches:
      # Pushing to the `main` branch
      # will trigger our workflow
      - main
    paths-ignore:
      - 'bin/**'
      - 'README.m'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2            
        with:
          # Fetch the entire Git history
          fetch-depth: 0
